title: Montenegro Roadtrip 2026
description: Interactive plan for a family roadtrip from Prague to Montenegro.
lang: cs-CZ
url: "https://me2d09.github.io"
baseurl: "/cernahora2026"

map:
  provider: openstreetmap
  mapy_api_key: "e5Q4FnVqeJSnxOHc_XNBB-PqI_7RSRDr1l0GEpUgflE"
  mapy_mapset: outdoor

exclude:
  - AGENTS.md
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
